[project]
name = "connectedpapers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pdfplumber>=0.11.4",
    "pip>=24.3.1",
    "requests>=2.32.3",
    "spacy>=3.8.2",
]
